### ISSUE TITLE
Unable to get user from mention on MS teams

### ISSUE THREAD

**Issue by nmwael** [finos/spring-bot#317]
I have this method but no matter what I do I cannot get the user mentioned (userA) in the chat to the bot:
```

    @ChatRequest(value = "echoUser {userA}",  description = "writeback user details")
    public MessageResponse echoUser(Addressable a, @ChatVariable("userA")  Optional<TeamsUser> userA) {
        if(userA.isPresent() && userA.isPresent()) {
            return new MessageResponse(a, "user  A<" + userA.get().getKey() + userA.get().getName() + ">");
        }else
        {
            return new MessageResponse(a, "user not found" );

        }
    }

```

Im very unsure if its just some kind of permission I need to give to my bot or application registration.. I can get the Addressable

**Comment by nmwael** [comment]
im double checking, something.. This might be related to the fact that Im running on mixed environments.. Trial for teams and msdn for azure..

**Comment by nmwael** [comment]
Ok remade this on a clean system, and still no luck.

**Comment by robmoffat** [comment]
HI @nmwael, sorry - for some reason I missed this notification.  Let me take a look today and get back to you

**Comment by robmoffat** [comment]
Right, so I checked out the latest code for `demo-bot` from `spring-bot-develop` branch and added your controller code above.  It mainly works for me: 

<img width="976" alt="Screenshot 2022-05-12 at 12 47 34" src="https://user-images.githubusercontent.com/568673/168068095-542d30cf-d0e3-40ca-a452-0c6d28a02c0e.png">

A couple of things:
- You can't mention _at all_ in a 1-1 chat, so there's no point trying to run this command 1-1.  That's why I'm demonstrating this in a Teams channel.  Also works in a teams multi-way chat.  
- As you can see, I kind of had trouble addressing the bot with `/`.  That should work, I'll raise a ticket.
- You're kind of "looking into" the teams object... if you want you can do something like this:

```
 @ChatRequest(value = "echoUser {userA}",  description = "writeback user details")
    public MessageResponse echoUser(Addressable a, @ChatVariable("userA")  Optional<TeamsUser> userA) {
        if(userA.isPresent() && userA.isPresent()) {
            return new MessageResponse(a, Message.of(Word.of("User "), userA.get()));
        }else
        {
            return new MessageResponse(a, "user not found" );

        }
    }
```

And that will produce this output:

<img width="979" alt="Screenshot 2022-05-12 at 12 50 49" src="https://user-images.githubusercontent.com/568673/168068656-42af6ed5-91b7-45b2-8aa3-a431a3019f10.png">

**Comment by robmoffat** [comment]
.. just checking something else - you did all the `ngrok` stuff and you can see the bot being called on your Java console, right?

**Comment by nmwael** [comment]
Yup

**Comment by nmwael** [comment]
The only difference are that the one working are being run from within
intellij and the one not are run from command line using spring boot fat jar

**Comment by robmoffat** [comment]
isn't that the other issue you raised?  I think it's better if we treat them separately.  

Let me see if I can help you debug this.  If you type `echoUser @somepersoninthechat`:

1.  Does the `echoUser` method get called?  
2. If so, what is the value of `userA`?

Let's start with that.

**Comment by nmwael** [comment]
Okay, yes the methods is called and I think you have addressed my problem.. I was @ someone who was not in the chat.. Is it not possible at all? Our chat bot is a system management bot, which configures stuff on users voice settings on teams. AFAIK the ms /who bot can check users not in chat, but is that because its not a 1-1 chat?

**Comment by robmoffat** [comment]
I think this is just a MS Teams thing - you can only mention people in the chat/channel. It's a pretty annoying restriction.  Also, you can't mention yourself!!  See:

- #317
